project:
  type: website
  output-dir: docs

website:
  title: "Jamarko"
  site-url: https://jamarko.com.np
  google-analytics: "G-PBPC8ZSXZC"
  image: assets\media\images\logos_and_banners\logo.png
  favicon: assets\media\images\logos_and_banners\logo.png
  twitter-card: true
  navbar:
    title: false
    logo: assets\media\images\logos_and_banners\logo.png
    logo-alt: Jamarko
    pinned: true
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Recycled
        href: pages\recycled.qmd
      - text: Upcycled
        href: pages\upcycled.qmd
      - text: Lokta
        href: pages\lokta.qmd
      - text: Customizations
        href: pages\customizations.qmd
      - text: Shop
        menu:
          - text: All Categories
            href: shop.qmd
          - text: Notebooks
            href: shop\notebooks\index.qmd
          - text: Greeting cards
            href: shop\greetingcards\index.qmd
          - text: Paper bags
            href: shop\paperbags\index.qmd
          - text: Photo frames
            href: shop\photoframes\index.qmd
          - text: Lampshades
            href: shop\lampshades\index.qmd
          - text: Wrapping papers
            href: shop\wrappingpapers\index.qmd
          - text: Boxes
            href: shop\boxes\index.qmd
          - text: Jewelry boxes
            href: shop\jewelryboxes\index.qmd
          - text: Pencils
            href: shop\pencils\index.qmd
      - text: About
        menu:
          - text: About Us
            href: about.qmd
          - text: Our Paper
            href: pages\ourpaper.qmd
          # - text: Our Team
          #   href:  ourteam.qmd
      - text: Contact Us
        href: contactus.qmd
    right:
      - icon: rss
        href: index.xml
  page-footer:
    center:
      - text: Copyright Â© 2001-<script>document.write( new Date().getFullYear() );</script>&nbsp;<a href="https://www.jamarko.com.np" target="_top">Jamarko</a>. All rights reserved. <br>Designed by <a href="https://www.mohitshrestha.com.np" target="_top">Mohit Shrestha</a>.

format:
  html:
    page-layout: full
    theme:
      - cosmo
      - brand
    css: /assets/css/styles.css # a user-defined customization
    toc: false



